export const getProducts = () => {
  return [
    {
      id: 0,
      tags: [],
      name: 'Cool Video Game',
      subtitle: 'Awesome super cool game',
      description: 'Super cool awesome discounted cool video game product for cheap',
      img: '0.jpg',
      alt: 'Alternative Text',
      price: 19.99,
      discount: 42,
      stock: 12,
    },
    {
      id: 1,
      tags: [],
      name: 'Tantalizing Technology',
      subtitle: 'Awesome super cool game',
      description: 'Super cool awesome discounted cool video game product for cheap',
      img: '1.jpg',
      alt: 'Alternative Text',
      price: 621.99,
      discount: 1,
      stock: 1,
    },
    {
      id: 2,
      tags: [],
      name: 'Super Cool Subscription',
      subtitle: 'Awesome super cool game',
      description: 'Super cool awesome discounted cool video game product for cheap',
      img: '2.jpg',
      alt: 'Alternative Text',
      price: 92.99,
      discount: 74,
      stock: 12,
    },
    {
      id: 3,
      tags: [],
      name: 'Radical Product',
      subtitle: 'Awesome super cool game',
      description: 'Super cool awesome discounted cool video game product for cheap',
      img: '3.jpg',
      alt: 'Alternative Text',
      price: 36.99,
      discount: 59,
      stock: 7,
    },
    {
      id: 4,
      tags: [],
      name: 'Sick Top-Up Card',
      subtitle: 'Awesome super cool game',
      description: 'Super cool awesome discounted cool video game product for cheap',
      img: '4.jpg',
      alt: 'Alternative Text',
      price: 129.99,
      discount: 24,
      stock: 32,
    },
    {
      id: 5,
      tags: [],
      name: 'Neat Gift Card',
      subtitle: 'Awesome super cool game',
      description: 'Super cool awesome discounted cool video game product for cheap',
      img: '5.jpg',
      alt: 'Alternative Text',
      price: 159.99,
      discount: 11,
      stock: 44,
    },
    {
      id: 6,
      tags: [],
      name: 'Bodacious Software',
      subtitle: 'Awesome super cool game',
      description: 'Super cool awesome discounted cool video game product for cheap',
      img: '6.jpg',
      alt: 'Alternative Text',
      price: 8.99,
      discount: 64,
      stock: 25,
    },
    {
      id: 7,
      tags: [],
      name: 'Nifty Digital Currency',
      subtitle: 'Awesome super cool game',
      description: 'Super cool awesome discounted cool video game product for cheap',
      img: '7.jpg',
      alt: 'Alternative Text',
      price: 299.99,
      discount: 8,
      stock: 12,
    },
  ];
};
